toubleshooting-system/app/main/forms.py
# -*- coding:utf-8 -*-
from flask_wtf import FlaskForm
from wtforms.fields import StringField, SubmitField, SelectMultipleField, SelectField, PasswordField
from wtforms.validators import DataRequired, IPAddress
from wtforms.fields.html5 import IntegerField
from wtforms import widgets

msg = '该字段不能为空'


class MultiCheckboxField(SelectMultipleField):
    """
    A multiple-select, except displays a list of checkboxes.

    Iterating the field will produce subfields, allowing custom rendering of
    the enclosed checkbox fields.
    """
    widget = widgets.ListWidget(prefix_label=False)
    option_widget = widgets.CheckboxInput()


# 网络线路表单
class NetLineForm(FlaskForm):
    name = StringField('线路名称', validators=[DataRequired(message=msg)])
    type = SelectField('线路类型', coerce=int, choices=[(1, '基本类型'), (2, '定制类型')],
                       validators=[DataRequired(message=msg)])
    submit = SubmitField('提交')


# 交换机表单
class SwitchForm(FlaskForm):
    description = StringField('描述', validators=[DataRequired(message=msg)])
    ip_address = StringField('IP地址', validators=[DataRequired(message=msg), IPAddress(message='无效的IP地址')])
    cer_id = SelectField('登录凭证', coerce=int, validators=[DataRequired(message=msg)])
    area_id = SelectField('区域', coerce=int, validators=[DataRequired(message=msg)])
    line_id = MultiCheckboxField('线路', coerce=int, validators=[DataRequired(message=msg)])
    level = IntegerField('层级', validators=[DataRequired(message=msg)])
    submit = SubmitField('提交')


# 检测IP表单
class CheckIPForm(FlaskForm):
    ip_address = StringField('IP地址', validators=[DataRequired(message=msg), IPAddress(message='无效的IP地址')])
    submit = SubmitField('检测')


# 区域表单
class AreaForm(FlaskForm):
    name = StringField('区域名称', validators=[DataRequired(message=msg)])
    submit = SubmitField('提交')


# IP地址表单
class IPAddressForm(FlaskForm):
    ip_address = StringField('IP地址', validators=[DataRequired(message=msg)])
    line_id = MultiCheckboxField('线路', coerce=int, validators=[DataRequired(message=msg)])
    area_id = SelectField('区域', coerce=int, validators=[DataRequired(message=msg)])
    submit = SubmitField('提交')


# 登录凭证表单
class CertificateForm(FlaskForm):
    name = StringField('凭证名称', validators=[DataRequired(message=msg)])
    username = StringField('用户名', validators=[DataRequired(message=msg)])
    password = PasswordField('密码', validators=[DataRequired(message=msg)])
    submit = SubmitField('提交')


# 端口扫描表单
class ScanPortForm(FlaskForm):
    ip_address = StringField('IP地址', validators=[DataRequired(message=msg)])
    submit = SubmitField('提交')

toubleshooting-system/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, forms

toubleshooting-system/app/main/views.py
# -*- coding:utf-8 -*-
from . import main
from flask import render_template, current_app, send_from_directory, redirect, request, flash, url_for, jsonify, abort
from flask_login import login_required
from ..models import Line, Switch, Area, IPAddress, Certificate
from .forms import NetLineForm, SwitchForm, CheckIPForm, AreaForm, IPAddressForm, CertificateForm, ScanPortForm
from app import db, redis_store
from ..tasks import remote_ping, portscanner
from ..tools import get_ips
import os
import re


# 首页
@main.route('/')
@login_required
def index():
    return redirect(url_for('main.check_ip'))


# 图标
@main.route('/favicon.ico')
def favicon():
    app = current_app._get_current_object()
    return send_from_directory(os.path.join(app.root_path, 'static'), 'favicon.ico', mimetype='image/vnd.microsoft.icon')


# 网络线路管理
@main.route('/netlines', defaults={'option': 'list', 'line_id': 0})
@main.route('/netlines/<string:option>', defaults={'line_id': 0}, methods=['GET', 'POST'])
@main.route('/netlines/<string:option>/<int:line_id>', methods=['GET', 'POST'])
@login_required
def netlines(option, line_id):
    page = request.args.get('page', 1, type=int)
    pagination = Line.query.order_by(Line.id).paginate(page, per_page=current_app.config['LINES_PER_PAGE'],
                                                       error_out=False)
    lines = pagination.items
    switchs_option = [(s.id, s.description) for s in Switch.query.all()]
    if option == 'add':
        form = NetLineForm()
        if form.validate_on_submit():
            if not Line.query.filter_by(name=form.name.data).first():
                custom_switchs = ''
                if form.type.data == 2:
                    custom_switchs_list = []
                    for key in request.values:
                        if re.match(r'^select\d+$', key):
                            custom_switchs_list.append((key, request.values.get(key)))
                    custom_switchs = ','.join([v[1] for v in sorted(custom_switchs_list, key=lambda x: int(x[0][6:]))])
                new_line = Line(name=form.name.data, type=form.type.data, custom_switchs=custom_switchs)
                db.session.add(new_line)
                db.session.commit()
                flash('添加线路成功', 'success')
                return redirect(url_for('main.netlines', page=page))
            flash('该线路已存在', 'error')
            return redirect(url_for('main.netlines', option='add', page=page))
        return render_template('main/netlines.html', form=form, page=page, switchs_option=switchs_option)
    if option == 'delete' and line_id:
        line = Line.query.get_or_404(line_id)
        for switch in Switch.query.all():
            if line in switch.lines:
                flash('该线路已经被使用，无法删除', 'error')
                return redirect(url_for('main.netlines', page=page))
        db.session.delete(line)
        db.session.commit()
        flash('删除线路成功', 'success')
        return redirect(url_for('main.netlines'))
    if option == 'edit' and line_id:
        line = Line.query.get_or_404(line_id)
        form = NetLineForm()
        if form.validate_on_submit():
            verify_line = Line.query.filter_by(name=form.name.data).first()
            if not verify_line or verify_line == line:
                custom_switchs = ''
                if form.type.data == 2:
                    custom_switchs_list = []
                    for key in request.values:
                        if re.match(r'^select\d+$', key):
                            custom_switchs_list.append((key, request.values.get(key)))
                    custom_switchs = ','.join([v[1] for v in sorted(custom_switchs_list, key=lambda x: int(x[0][6:]))])
                line.name = form.name.data
                line.type = form.type.data
                line.custom_switchs = custom_switchs
                flash('修改线路成功', 'success')
                return redirect(url_for('main.netlines', page=page))
            flash('该线路已存在', 'error')
            return redirect(url_for('main.netlines', option='edit', line_id=line.id, page=page))
        form.name.data = line.name
        form.type.data = line.type
        return render_template('main/netlines.html', form=form, page=page, switchs_option=switchs_option,
                               custom_switchs=line.custom_switchs.split(','))
    return render_template('main/netlines.html', lines=lines, pagination=pagination, page=page)


# 交换机管理
@main.route('/switchs', defaults={'option': 'list', 'switch_id': 0})
@main.route('/switchs/<string:option>', defaults={'switch_id': 0}, methods=['GET', 'POST'])
@main.route('/switchs/<string:option>/<int:switch_id>', methods=['GET', 'POST'])
@login_required
def switchs(option, switch_id):
    page = request.args.get('page', 1, type=int)
    pagination = Switch.query.order_by(Switch.id).\
        paginate(page, per_page=current_app.config['SWITCHS_PER_PAGE'], error_out=False)
    switchs = pagination.items
    line_choices = [(l.id, l.name) for l in Line.query.filter_by(type=1).all()]
    area_choices = [(a.id, a.name) for a in Area.query.all()]
    cer_choices = [(c.id, c.name) for c in Certificate.query.all()]
    if option == 'add':
        form = SwitchForm()
        form.line_id.choices = line_choices
        form.area_id.choices = area_choices
        form.cer_id.choices = cer_choices
        if form.validate_on_submit():
            if not Switch.query.filter_by(ip_address=form.ip_address.data).first():
                new_switch = Switch(description=form.description.data, ip_address=form.ip_address.data,
                                    area_id=form.area_id.data, cer_id=form.cer_id.data,
                                    level=form.level.data)
                new_switch.lines = [Line.query.get_or_404(line_id) for line_id in form.line_id.data]
                db.session.add(new_switch)
                db.session.commit()
                flash('添加交换机成功', 'success')
                return redirect(url_for('main.switchs', page=page))
            flash('该交换机已存在', 'error')
            return redirect(url_for('main.switchs', option='add', page=page))
        return render_template('main/switchs.html', form=form, page=page)
    if option == 'delete' and switch_id:
        switch = Switch.query.get_or_404(switch_id)
        db.session.delete(switch)
        db.session.commit()
        flash('删除交换机成功', 'success')
        return redirect(url_for('main.switchs'))
    if option == 'edit' and switch_id:
        switch = Switch.query.get_or_404(switch_id)
        form = SwitchForm()
        form.line_id.choices = line_choices
        form.area_id.choices = area_choices
        form.cer_id.choices = cer_choices
        if form.validate_on_submit():
            verify_switch = Switch.query.filter_by(ip_address=form.ip_address.data).first()
            if not verify_switch or verify_switch == switch:
                switch.description = form.description.data
                switch.ip_address = form.ip_address.data
                switch.area_id = form.area_id.data
                switch.cer_id = form.cer_id.data
                switch.lines = [Line.query.get_or_404(line_id) for line_id in form.line_id.data]
                switch.level = form.level.data
                flash('修改交换机成功', 'success')
                return redirect(url_for('main.switchs', page=page))
            flash('该交换机已存在', 'error')
            return redirect(url_for('main.switchs', option='edit', switch_id=switch.id, page=page))
        form.description.data = switch.description
        form.ip_address.data = switch.ip_address
        form.area_id.data = switch.area_id
        form.cer_id.data = switch.cer_id
        form.line_id.data = [line.id for line in switch.lines]
        form.level.data = switch.level
        return render_template('main/switchs.html', form=form, page=page)
    return render_template('main/switchs.html', switchs=switchs, pagination=pagination, page=page)


# IP检测
@main.route('/check_ip', methods=['GET', 'POST'])
@login_required
def check_ip():
    ip_address = request.args.get('ip_address', '', type=str)
    form = CheckIPForm()
    if form.validate_on_submit():
        if not IPAddress.query.filter_by(ip_address=form.ip_address.data).first():
            flash('该IP为外部IP，暂不支持查询', 'warning')
            return redirect(url_for('main.check_ip'))
        return redirect(url_for('main.check_ip', ip_address=form.ip_address.data))
    form.ip_address.data = ip_address
    if ip_address != '':
        redis_store.delete('check_ip_%s' % ip_address)
        ip = IPAddress.query.filter_by(ip_address=ip_address).first()
        for line in ip.lines:
            if line.type == 1:
                switchs_in_line = [switch for switch in Switch.query.filter_by(area_id=ip.area_id).all()
                                   if line in switch.lines]
            else:
                switchs_in_line = [Switch.query.get(switch_id) for switch_id in line.custom_switchs.split(',')]
            for switch in switchs_in_line:
                remote_ping.delay(ip_address, switch.ip_address, switch.certificate.username,
                                  switch.certificate.password, line.id, switch.id)
        flash('IP检测中，请注意查看下方结果', 'success')
        return render_template('main/check_ip.html', form=form)
    return render_template('main/check_ip.html', form=form)


# 区域管理
@main.route('/areas', defaults={'option': 'list', 'area_id': 0})
@main.route('/areas/<string:option>', defaults={'area_id': 0}, methods=['GET', 'POST'])
@main.route('/areas/<string:option>/<int:area_id>', methods=['GET', 'POST'])
@login_required
def areas(option, area_id):
    page = request.args.get('page', 1, type=int)
    pagination = Area.query.order_by(Area.id).paginate(page, per_page=current_app.config['AREAS_PER_PAGE'],
                                                       error_out=False)
    areas = pagination.items
    if option == 'add':
        form = AreaForm()
        if form.validate_on_submit():

toubleshooting-system/app/templates/main/areas.html
{% extends "main/index.html" %}
{% from "wtf.html" import quick_form %}
{%  from "pagination.html" import render_pagination %}

{% block content %}
{% if areas %}
    <div class="container-fluid">
    <div class="row" id="plus-row">
        <a href="{{ url_for('main.areas', option='add', page=page) }}" class="btn btn-success btn-sm" id="plus-button" role="button"><i class="fa fa-plus"></i> 新增</a>
    </div>
    <table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th id="th-id">ID</th>
            <th>区域名</th>
            <th id="th-option">操作</th>
        </tr>
    </thead>
    <tbody>
    {% for area in areas %}
        <tr>
            <td>{{ area.id }}</td>
            <td>{{ area.name }}</td>
            <td>
                <a href="{{ url_for('main.areas', option='edit', area_id=area.id, page=page) }}" class="btn btn-warning btn-xs" role="button"><i class="fa fa-edit"></i> 修改</a>
                <!-- Button trigger modal -->
                <a  class="btn btn-danger btn-xs" role="button" data-toggle="modal" data-target="#DeleteArea{{ area.id }}"><i class="fa fa-trash"></i> 删除</a>
                <!-- Modal -->
                <div class="modal fade" id="DeleteArea{{ area.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">删除确认</h4>
                      </div>
                      <div class="modal-body">
                       确定要删除区域（{{ area.name }}）？
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                        <a href="{{ url_for('main.areas', option='delete', area_id=area.id) }}" role="button" class="btn btn-primary">确定</a>
                      </div>
                    </div>
                  </div>
                </div>

            </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
    <div class="row" id="pagination-row">{{ render_pagination(pagination, '.areas') }}</div>
    </div>
    {% elif not form %}
    <div class="row" id="no-data-notify">目前还没有添加区域，请前往<a href="{{ url_for('main.areas', option='add', page=page) }}" style="color:red">添加</a></div>
{% endif %}
{% if form %}
    {{ quick_form(form, button_map={'submit': 'info'}) }}
    <hr>
    <a href="{{ url_for('main.areas', page=page) }}"><i class="fa fa-arrow-left"></i> 返回列表</a>
{% endif %}
{% endblock %}

toubleshooting-system/app/templates/main/index.html
{% from "_flashed_messages.html" import flashed_messages %}
{% block doc -%}
<!DOCTYPE html>
<html {% block html_attribs %}lang="en"{% endblock html_attribs %}>
{%- block html %}
  <head>
   {%- block head %}
    {%- block metas %}
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {%- endblock metas %}

    <title>{% block title %}网宿科技--排错系统 V1.0{% endblock title %}</title>

    {%- block styles %}
    <!-- Bootstrap -->
    <link href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css', _external=True) }}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{{ url_for('static', filename='font-awesome/css/font-awesome.min.css', _external=True) }}" rel="stylesheet">
{#    <!-- NProgress -->#}
{#    <link href="{{ url_for('static', filename='nprogress/css/nprogress.css', _external=True) }}" rel="stylesheet">#}
{#    <!-- iCheck -->#}
{#    <link href="{{ url_for('static', filename='iCheck/skins/flat/green.css', _external=True) }}" rel="stylesheet">#}
{#	#}
{#    <!-- bootstrap-progressbar -->#}
{#     <link href="{{ url_for('static', filename='bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css', _external=True) }}" rel="stylesheet">#}
{#    <!-- JQVMap -->#}
{#    <link href="{{ url_for('static', filename='jqvmap/css/jqvmap.min.css', _external=True) }}" rel="stylesheet">#}
{#    <!-- bootstrap-daterangepicker -->#}
{#    <link href="{{ url_for('static', filename='bootstrap-daterangepicker/css/daterangepicker.css', _external=True) }}" rel="stylesheet">#}

    <!-- Custom Theme Style -->
    <link href="{{ url_for('static', filename='build/css/custom.min.css', _external=True) }}" rel="stylesheet">

    <!-- LobiboxStyle -->
    <link href="{{ url_for('static', filename='lobibox/css/lobibox.min.css', _external=True) }}" rel="stylesheet">

     <!-- mLoading Style -->
    <link href="{{ url_for('static', filename='mloading/css/jquery.mloading.css', _external=True) }}" rel="stylesheet">

     <!-- MyStyle -->
    <link href="{{ url_for('static', filename='css/mystyles.css', _external=True) }}" rel="stylesheet">
    {%- endblock styles %}
   {%- endblock head %}
  </head>

  <body {% block body_attribs %}class="nav-md" id="html-body"{% endblock body_attribs %}>
  {% block body -%}
    <div class="container body">
      <div class="main_container">
      {%- block navbar %}
      {%- block sidebar %}
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="{{ url_for('main.index') }}" class="site_title"><i class="fa fa-desktop"></i> <span>排错系统 V1.0</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile clearfix">
              <div class="profile_pic">
                <img src="{{ url_for('static', filename='images/img.jpg', _external=True) }}" alt="..." class="img-circle profile_img">
              </div>
              <div class="profile_info">
                <span>欢迎您,</span>
                <h2>{{ current_user.username }}</h2>
              </div>
            </div>
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <ul class="nav side-menu">
                  <li><a href="{{ url_for('main.index') }}"><i class="fa fa-home"></i> 主页 </a>
                  <li><a href="{{ url_for('main.check_ip') }}"><i class="fa fa-rss"></i> IP检测 </a>
                  <li><a href="{{ url_for('main.scan_port') }}"><i class="fa fa-search"></i> 端口扫描 </a>
                  </li>
                  <li><a><i class="fa fa-cogs"></i>基础设置 <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{{ url_for('main.areas') }}">区域管理</a></li>
                      <li><a href="{{ url_for('main.netlines') }}">线路管理</a></li>
                      <li><a href="{{ url_for('main.certificates') }}">凭证管理</a></li>
                      <li><a href="{{ url_for('main.switchs') }}">交换机管理</a></li>
                      <li><a href="{{ url_for('main.ip_addresses') }}">业务IP管理</a></li>
                    </ul>
                  </li>
                    {% if current_user.is_admin %}
                    <li><a href="{{ url_for('auth.users') }}"><i class="fa fa-users"></i> 用户管理 </a>
                    {% endif %}
                  </li>
                </ul>
              </div>
            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="退出" href="{{ url_for('auth.logout') }}">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>
            <!-- /menu footer buttons -->
          </div>
        </div>
        {%- endblock sidebar %}
        {%- block topbar %}
        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="{{ url_for('static', filename='images/img.jpg', _external=True) }}" alt="">{{ current_user.username }}
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                      {% if current_user.is_admin %}
                           <li><a href="{{ url_for('auth.admin_change_password') }}"><i class="fa fa-edit pull-right"></i> 修改密码</a></li>
                      {% else %}
                   <li><a href="{{ url_for('auth.change_password') }}"><i class="fa fa-edit pull-right"></i> 修改密码</a></li>
                      {% endif %}
                    <li><a href="{{ url_for('auth.logout') }}"><i class="fa fa-sign-out pull-right"></i> 退出</a></li>
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->
        {%- endblock topbar %}
        {%- endblock navbar %}
        <!-- page content -->
        <div class="right_col" role="main">
        {%- block content %}

        {%- endblock content %}
        </div>
    </div>
    </div>


    {% block scripts %}
    <!-- jQuery -->
    <script src="{{ url_for('static', filename='jquery/js/jquery.min.js', _external=True) }}"></script>
    <!-- Bootstrap -->
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js', _external=True) }}"></script>
{#    <!-- FastClick -->#}
{#    <script src="{{ url_for('static', filename='fastclick/js/fastclick.js', _external=True) }}"></script>#}
{#    <!-- NProgress -->#}
{#    <script src="{{ url_for('static', filename='nprogress/js/nprogress.js', _external=True) }}"></script>#}
{#    <!-- Chart.js -->#}
{#    <script src="{{ url_for('static', filename='Chartjs/js/Chart.min.js', _external=True) }}"></script>#}
{#    <!-- gauge.js -->#}
{#    <script src="{{ url_for('static', filename='gaugejs/js/gauge.min.js', _external=True) }}"></script>#}
{#    <!-- bootstrap-progressbar -->#}
{#    <script src="{{ url_for('static', filename='bootstrap-progressbar/js/bootstrap-progressbar.min.js', _external=True) }}"></script>#}
{#    <!-- iCheck -->#}
{#    <script src="{{ url_for('static', filename='iCheck/js/icheck.min.js', _external=True) }}"></script>#}
{#    <!-- Skycons -->#}
{#    <script src="{{ url_for('static', filename='skycons/js/skycons.js', _external=True) }}"></script>#}
{#    <!-- Flot -->#}
{#    <script src="{{ url_for('static', filename='Flot/js/jquery.flot.js', _external=True) }}"></script>#}
{#    <script src="{{ url_for('static', filename='Flot/js/jquery.flot.pie.js', _external=True) }}"></script>#}
{#    <script src="{{ url_for('static', filename='Flot/js/jquery.flot.time.js', _external=True) }}"></script>#}
{#    <script src="{{ url_for('static', filename='Flot/js/jquery.flot.stack.js', _external=True) }}"></script>#}
{#    <script src="{{ url_for('static', filename='Flot/js/jquery.flot.resize.js', _external=True) }}"></script>#}
{#    <!-- Flot plugins -->#}
{#    <script src="{{ url_for('static', filename='flotorderbars/js/jquery.flot.orderBars.js', _external=True) }}"></script>#}
{#    <script src="{{ url_for('static', filename='flot-spline/js/jquery.flot.spline.min.js', _external=True) }}"></script>#}
{#    <script src="{{ url_for('static', filename='flotcurvedlines/js/curvedLines.js', _external=True) }}"></script>#}
{#    <!-- DateJS -->#}
{#    <script src="{{ url_for('static', filename='DateJS/js/date.js', _external=True) }}"></script>#}
{#    <!-- JQVMap -->#}
{#    <script src="{{ url_for('static', filename='jqvmap/js/jquery.vmap.min.js', _external=True) }}"></script>#}
{#    <script src="{{ url_for('static', filename='jqvmap/js/maps/jquery.vmap.world.js', _external=True) }}"></script>#}
{#    <script src="{{ url_for('static', filename='jqvmap/js/jquery.vmap.sampledata.js', _external=True) }}"></script>#}
{#    <!-- bootstrap-daterangepicker -->#}
{#    <script src="{{ url_for('static', filename='moment/js/moment.min.js', _external=True) }}"></script>#}
{#    <script src="{{ url_for('static', filename='bootstrap-daterangepicker/js/daterangepicker.js', _external=True) }}"></script>#}

    <!-- Custom Theme Scripts -->
    <script src="{{ url_for('static', filename='build/js/custom.min.js', _external=True) }}"></script>

    <!-- Lobibox Scripts -->
    <script src="{{ url_for('static', filename='lobibox/js/lobibox.min.js', _external=True) }}"></script>

     <!-- mLoading Scripts -->
    <script src="{{ url_for('static', filename='mloading/js/jquery.mloading.js', _external=True) }}"></script>

    <!-- Validate Scripts -->
    <script src="{{ url_for('static', filename='validate/js/jquery.validate.min.js', _external=True) }}"></script>
    <script src="{{ url_for('static', filename='validate/js/messages_zh.min.js', _external=True) }}"></script>
     <script src="{{ url_for('static', filename='validate/js/additional-methods.js', _external=True) }}"></script>
    {{ flashed_messages() }}
    {%- endblock scripts %}
  {%- endblock body %}
  </body>
{%- endblock html %}
</html>
{% endblock doc -%}